nombres = input("Nombres: ")
nombres = nombres.lower().strip()
nombres = nombres.replace(" ", ".")
apellidos = input("Apellidos: ")
apellidos = apellidos.lower().strip()
apellidos = apellidos.replace(" ", ".")
empresa = input("Nombre Empresa: ")
empresa = empresa.lower().strip()
empresa = empresa.replace(" ", "")
extension_dominio = input("Extensión Dominio: ")
extension_dominio = extension_dominio.lower().strip()
print(f"Email: {nombres}.{apellidos}@{empresa}{extension_dominio}")